"""
Simulated inference endpoint for high-concurrency testing.

Replaces the real Anthropic API at concurrency levels 25, 50, 100
as defined in the hybrid testing approach (Chapter 3, Part 6).

Behaviour:
  /simulate/inference — Waits for calibrated delay, returns fixed response
  /simulate/stream    — Emits tokens at calibrated rate via SSE

Calibration parameters are loaded from simulated_endpoint/calibration.json,
which is generated by scripts/calibrate_simulator.py after running
preliminary real API tests.

Runs on port 9000 (separate from framework servers on port 8000).
Uses Tornado as the HTTP server — this is a utility service, not a
benchmarked framework.

Usage:
  python simulated_endpoint/simulator.py
"""

import asyncio
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import tornado.ioloop
import tornado.web
import tornado.httpserver

# ---------------------------------------------------------------------------
# Default calibration values (overwritten by calibration.json)
# ---------------------------------------------------------------------------
DEFAULT_CALIBRATION = {
    "median_response_time_s": 2.5,       # Median real API response time
    "tokens_per_second": 50.0,           # Observed real API token rate
    "total_output_tokens": 256,          # Average response token count
    "model": "claude-haiku-4-5-20251001",
    "input_tokens": 33,
}

CALIBRATION_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "calibration.json"
)


def load_calibration():
    """Load calibration parameters from file, or use defaults."""
    if os.path.exists(CALIBRATION_FILE):
        with open(CALIBRATION_FILE, "r", encoding="utf-8") as f:
            params = json.load(f)
        print(f"Loaded calibration from {CALIBRATION_FILE}")
        return params
    else:
        print(f"No calibration file found at {CALIBRATION_FILE}")
        print("Using default calibration values")
        return DEFAULT_CALIBRATION.copy()


# Load once at startup
CALIBRATION = load_calibration()

# Pre-generate the fixed response text (same length as real API responses)
FIXED_RESPONSE_TEXT = (
    "Generative AI refers to artificial intelligence systems that can create "
    "new content such as text, images, code, and other media. In modern web "
    "applications, generative AI is integrated through API-based services "
    "provided by companies like OpenAI, Google, and Anthropic. Web applications "
    "send user input to these inference APIs and receive generated responses. "
    "Common use cases include chatbots for customer support, content generation "
    "for marketing, code assistance for developers, and personalized "
    "recommendations. The integration typically follows a request-response "
    "pattern where the web backend acts as an orchestration layer between "
    "the user interface and the AI inference service."
)


# ---------------------------------------------------------------------------
# Endpoint: /simulate/inference — Fixed delay + fixed response
# ---------------------------------------------------------------------------

class SimulatedInferenceHandler(tornado.web.RequestHandler):
    """Simulate a standard inference call with calibrated delay."""

    async def post(self):
        delay = CALIBRATION["median_response_time_s"]

        # Simulate the API processing time
        await asyncio.sleep(delay)

        response = {
            "response": FIXED_RESPONSE_TEXT,
            "model": CALIBRATION["model"],
            "usage": {
                "input_tokens": CALIBRATION["input_tokens"],
                "output_tokens": CALIBRATION["total_output_tokens"],
            },
        }

        self.set_header("Content-Type", "application/json")
        self.write(json.dumps(response))


# ---------------------------------------------------------------------------
# Endpoint: /simulate/stream — Token-by-token SSE at calibrated rate
# ---------------------------------------------------------------------------

class SimulatedStreamHandler(tornado.web.RequestHandler):
    """Simulate streaming inference with calibrated token rate."""

    async def post(self):
        tokens_per_second = CALIBRATION["tokens_per_second"]
        total_tokens = CALIBRATION.get("streaming_chunks", 12)
        delay_per_token = 1.0 / tokens_per_second

        self.set_header("Content-Type", "text/event-stream")
        self.set_header("Cache-Control", "no-cache")
        self.set_header("X-Accel-Buffering", "no")

        # Split the fixed response into simulated tokens (words)
        words = FIXED_RESPONSE_TEXT.split()

        # Distribute words across the total token count
        # If fewer words than tokens, repeat; if more, truncate
        token_chunks = []
        for i in range(total_tokens):
            if i < len(words):
                token_chunks.append(words[i] + " ")
            else:
                token_chunks.append(". ")

        for i, chunk in enumerate(token_chunks, 1):
            await asyncio.sleep(delay_per_token)

            event_data = json.dumps({"token": chunk, "index": i})
            self.write(f"data: {event_data}\n\n")
            self.flush()

        # Signal stream completion
        self.write(f"data: {json.dumps({'done': True, 'total_tokens': total_tokens})}\n\n")
        self.flush()


# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

class HealthHandler(tornado.web.RequestHandler):
    """Health check showing current calibration parameters."""

    def get(self):
        self.set_header("Content-Type", "application/json")
        self.write(json.dumps({
            "status": "ok",
            "service": "simulated_endpoint",
            "calibration": CALIBRATION,
        }))


# ---------------------------------------------------------------------------
# Application setup
# ---------------------------------------------------------------------------

SIMULATOR_PORT = 9000

def make_app():
    return tornado.web.Application([
        (r"/simulate/inference", SimulatedInferenceHandler),
        (r"/simulate/stream", SimulatedStreamHandler),
        (r"/health", HealthHandler),
    ])


if __name__ == "__main__":
    app = make_app()
    server = tornado.httpserver.HTTPServer(app)
    server.listen(SIMULATOR_PORT)
    print(f"Simulated endpoint listening on http://127.0.0.1:{SIMULATOR_PORT}")
    print(f"Calibration: {json.dumps(CALIBRATION, indent=2)}")
    tornado.ioloop.IOLoop.current().start()